
title: AOTCA2017
email: your-email@domain.com
description: >
  Welcome to AOTCA International Tax Conference 2017 Towards a Fair and Efficient Tax System

baseurl: ""
url: "http://www.aotca2017manila.com/"


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
